#!/usr/bin/env bash

go mod tidy

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  echo "Go mod is out of date!"
  exit 1
fi

go fmt main.go

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  echo "bad go formatting!"
  exit 1
fi


helm lint --with-subcharts charts/file-share

docker build --no-cache . || exit 1